# Copyright (C) 2020 Casper Meijn <casper@meijn.net>
#
# SPDX-License-Identifier: CC0-1.0

[package]
name = "nmea-test-messages"
version = "0.1.0"
edition = "2021"

[dependencies]
pcap-file = "2.0.0"
